language: php
php:
    - "5.5"
before_install:
    - sudo apt-get update
    - sudo apt-get install php-pear php5-dev
    - printf "\n" | sudo pecl install mongo
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - composer install

script: vendor/bin/phpunit

notifications:
    email:
      - krishnanunni@suyati.com
      - nmohanan@suyati.com
      - tkannippoyil@suyati.com